{{- if and (eq .Values.architecture "replication") (gt (.Values.replica.replicaCount | int) 0) }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "redis.replica.serviceName" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "redis.labels" . | nindent 4 }}
    app.kubernetes.io/component: replica
    {{- if .Values.replica.service.labels }}
    {{- toYaml .Values.replica.service.labels | nindent 4 }}
    {{- end }}
  {{- if .Values.replica.service.annotations }}
  annotations: {{- toYaml .Values.replica.service.annotations | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.replica.service.type }}
  {{- if and .Values.replica.service.loadBalancerIP (eq .Values.replica.service.type "LoadBalancer") }}
  loadBalancerIP: {{ .Values.replica.service.loadBalancerIP }}
  {{- end }}
  {{- if and .Values.replica.service.loadBalancerSourceRanges (eq .Values.replica.service.type "LoadBalancer") }}
  loadBalancerSourceRanges: {{- toYaml .Values.replica.service.loadBalancerSourceRanges | nindent 4 }}
  {{- end }}
  {{- if and (eq .Values.replica.service.type "LoadBalancer") .Values.replica.service.externalTrafficPolicy }}
  externalTrafficPolicy: {{ .Values.replica.service.externalTrafficPolicy }}
  {{- end }}
  {{- if .Values.replica.service.sessionAffinity }}
  sessionAffinity: {{ .Values.replica.service.sessionAffinity }}
  {{- if .Values.replica.service.sessionAffinityConfig }}
  sessionAffinityConfig: {{- toYaml .Values.replica.service.sessionAffinityConfig | nindent 4 }}
  {{- end }}
  {{- end }}
  ports:
    - name: tcp-redis
      port: {{ .Values.replica.service.port }}
      targetPort: redis
      {{- if and .Values.replica.service.nodePort (or (eq .Values.replica.service.type "NodePort") (eq .Values.replica.service.type "LoadBalancer")) }}
      nodePort: {{ .Values.replica.service.nodePort }}
      {{- end }}
    {{- if .Values.metrics.enabled }}
    - name: metrics
      port: {{ .Values.metrics.port | default 9121 }}
      targetPort: metrics
    {{- end }}
  selector: {{- include "redis.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: replica
{{- end }}
